 // Load your images on page-load
 function preloader() {
    const imagesList = [
       "./img/img-1.jpg",
       "./img/img-2.jpg",
       "./img/img-3.jpg"
    ];
    const images = [];
    for (let i = 0; i < imagesList.length; i++) {
        images[i] = new Image();
        images[i].src = imagesList[i];
    }

    // Images ready to be used:
    console.log(`Preloaded images:\n\t${images[0].src}\n\t${images[1].src}\n\t${images[2].src}`);
};    
window.addEventListener("load", preloader);



const btns = document.querySelectorAll("button");

const resources = {
    solar: {
        headingContent: "Solar Power",
        imgUrl: "./img/img-1.jpg",
        imgAlt: "solar panels",
        bodyText: "  This common renewable, green energy source is usually produced using photovoltaic cells that capture sunlight and turn it into electricity. Solar power is also used to heat buildings and for hot water as well as for cooking and lighting. Solar power has now become affordable enough to be used for domestic purposes including garden lighting, although it is also used on a larger scale to power entire neighbourhoods. <br> Solar energy is the energy generated by the sun and radiated through space, mostly as visible and near-infrared light. It sustains nearly all life on Earth. When sunlight strikes a surface on our planet, thermal energy, also called heat, is produced. \
        This thermal energy drives several global phenomena, including the water cycle, wind patterns and ocean currents. Photosynthesis, the process by which plants produce their own food, occurs through the conversion of sunlight into chemical energy.The natural\
         conversion of sunlight into other forms of energy has inspired the ways humans capture and use this energy. Broadly speaking, there are two methods of using solar energy: passive and active. Passive solar methods are those that use sunlight directly (e.g., lighting and heating a room through a window). Active methods use technology to convert solar energy into a secondary form (e.g., a fluid or electricity) that has its own use.\
        <br><em><strong><small>	Adam Jones, et al. Advances in parabolic trough solar power technology. J. Sol. Energy Eng. 124.2 (2002): 109-125.\
        </small></strong></em>", 
        
    },

    wind: {
        headingContent: "Wind Power",
        imgUrl: "./img/img-2.jpg",
        imgAlt: "small wind turbine",
        bodyText: " Wind energy is energy obtained from moving air. The motion results from the heating and cooling of the Earth; thus, wind energy is an indirect form of solar energy. It is normally turned into useful energy by the action of wind currents on moving surfaces such as the sails of a ship or the blades of a windmill. Wind energy is one of the oldest forms of energy used to supplement human muscle. Windmills and other spinning wind-energy devices - more accurately known as wind turbines - were used for grinding grain by the 7th century AD, and were in wide use for this purpose and for pumping water by the Middle Ages; they were brought by the French to Canada in the 17th century and were commonly used for grinding grain. Ships have used sails for at least 3000-4000 years. Before the advent of rural electrification systems, wind turbines were also used to generate electricity on farms in N America, notably on the Canadian prairies.<br> The advantage of wind-energy systems is that they tap an inexhaustible energy source that has no competing uses; hence, there is no fuel cost. The disadvantage is that wind conditions are unpredictable: they are subject to gusting and becalming, to daily and seasonal variations in strength, and to interactions with local topographic features. To meet a continuous demand such as a community's lighting and heating, a wind-energy system must either be integrated with other energy sources or include a means of storing energy for use during calm periods. If the demand is not continuous (eg, in agricultural water systems or unscheduled water transportation) wind energy can be employed very usefully.\
        The reawakening of interest in wind-energy conversion systems is the result of increasing energy demands and the relatively high costs of conventional energy sources. New wind-energy conversion equipment uses advanced aerodynamic features, modern structural design and new materials. The revival encompasses not only land-based systems but also commercial marine applications. New sail configurations have been devised to improve ship performance dramatically. However, the greatest effort has been focused on land-based generation of electric power using high-speed wind turbines.\
        <br><em><strong><small>	Gipe, P. (2004). Wind power. Wind Engineering, 28(5), 629-631.\
        </small></strong></em>", 
    
    },
    geo: {
        headingContent: "Hydropower",
        imgUrl: "./img/img-3.jpg",
        imgAlt: "Hydropower",
        bodyText: " People have a long history of using the force of water flowing in streams and rivers to produce mechanical energy. Hydropower was one of the first sources of energy used for electricity generation, and until 2019, hydropower was the largest source of total annual U.S. renewable electricity generation.\
        <br>In 2021, hydroelectricity accounted for about 6.3% of total U.S. utility-scale1 electricity generation and 31.5% of total utility-scale renewable electricity generation. Hydroelectricity’s share of total U.S. electricity generation has decreased over time, mainly because of increases in electricity generation from other sources.\
        <br><em><strong><small>	Bartle, A. (2002). Hydropower potential and development activities. Energy policy, 30(14), 1231-1239.\
        </small></strong></em>", 
    }
};

 const title = document.getElementById("title");
 const img = document.getElementById("img");
 const content = document.getElementById("content");

function handleSelection(e) {
 
 for (let i = 0; i < btns.length; i++) {
     if (btns[i].hasAttribute("id")) {
         btns[i].removeAttribute("id");
     }
 }

 let currentButton = e.target;

 if (currentButton.textContent === "Solar Power") {
     currentButton.setAttribute("id", "active-button");
 }
 if (currentButton.textContent === "Wind Power") {
     currentButton.setAttribute("id", "active-button");

 }
 if (currentButton.textContent === "Hydropower") {
     currentButton.setAttribute("id", "active-button");

 }

 if (currentButton.textContent === "Solar Power") {
     title.innerHTML = `${resources.solar.headingContent}`;
     img.innerHTML = `<img src="${resources.solar.imgUrl} "alt="${resources.solar.imgAlt}">`;
     content.innerHTML = `${resources.solar.bodyText}`
 } else if (currentButton.textContent === "Wind Power") {
     title.innerHTML = `${resources.wind.headingContent}`;
     img.innerHTML = `<img src="${resources.wind.imgUrl} "alt="${resources.wind.imgAlt}">`;
     content.innerHTML = `${resources.wind.bodyText}`
 } else {
     title.innerHTML = `${resources.geo.headingContent}`;
     img.innerHTML = `<img src="${resources.geo.imgUrl} "alt="${resources.geo.imgAlt}">`;
     content.innerHTML = `${resources.geo.bodyText}`
 }
}
    

 for (i = 0; i < btns.length; i++) {   
        btns[i].addEventListener("click", handleSelection);
    }
